<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="ClientApp\src\app\components\layout\" />
    <Folder Include="ClientApp\src\app\components\user-list\" />
    <Folder Include="ClientApp\src\assets\" />
  </ItemGroup>

	<ItemGroup>
		<Compile Remove="EventHub.Infrastructure\**" />
		<Content Remove="EventHub.Infrastructure\**" />
		<None Remove="EventHub.Infrastructure\**" />
	</ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="BouncyCastle.NetCore" Version="2.2.1" />
  </ItemGroup>

</Project>
